version: 2


steps: &steps
  steps:
#    - restore_cache:
#        keys:
#          - cache-{{ .Environment.CIRCLE_JOB }}
    - checkout
    - run:
        name: Install package dependencies env
        command: sudo apt-get update && sudo apt install jags && sudo apt-get install -y r-cran-rgl
    - run:
        name: Install Matrix
        command: R -e "devtools::install_cran('Matrix')"
    - run:
        name: Install neuroconductor
        command: R -e "source('https://neuroconductor.org/neurocLite.R')"
    - run:
        name: Install package neuroconductor dependencies manually
        command: Rscript -e "neuro_install(c('ITKR', 'ANTsRCore','ANTsR'))"
    - run:
        name: Install package dependencies manually
        command: Rscript -e "install.packages(c('wesanderson','ggthemes','ggstatsplot'))"
    - run:
        name: Install ANTsRNet
        command: Rscript -e "devtools::install_github( 'ANTsX/ANTsRNet' ) "
    - run:
        name: Install patchMatchR
        command: Rscript -e "devtools::install_github( 'stnava/patchMatchR' ) "
    - run:
        name: Build package
        command: R CMD build .
    - run:
        name: Check package
        command: R CMD check *tar.gz
#    - store_artifacts:
#        path: ci4rB.Rcheck/
#    - save_cache:
#        key: cache-{{ .Environment.CIRCLE_JOB }}
#        paths:
#          - "/usr/local/lib/R/site-libraryX"

jobs:
  release:
    docker:
      - image: rocker/verse:3.6.0
    <<: *steps
  oldrel:
    docker:
      - image: rocker/verse:3.5.3
    <<: *steps
  devel:
    docker:
      - image: rocker/verse:devel
    <<: *steps

workflows:
  version: 2
  all:
    jobs:
      - release
      - oldrel
#      - devel
